version: '3.8'
services:
#   Provision the app before starting it only for dev env
    provision:
        image: node:14-alpine
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["npm", "i"]

#   docker-compose up app-dev ( after build )
    app-dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev

        environment:
            - REQUEST_TIMEOUT=60000
            - TEMPLATES_DIR=public/html
            - ENV=dev
            - ADMIN_USERNAME=root
            - ADMIN_PASSWORD=toor

        volumes:
            - .:/app

        ports:
            - "80:80"

        restart: unless-stopped

        working_dir: /app

        entrypoint: ["pm2-runtime", "start", "dev.ecosystem.config.js"]
