version: '3.8'
services:
#   Provision the app before starting it only for dev env
    provision:
        image: node:14-alpine
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["npm", "i"]

#   docker-compose up app ( after build )
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev

        volumes:
            - .:/app
        ports:
            - "80:80"
        working_dir: /app
        entrypoint: ["pm2-runtime", "start", "dev.ecosystem.config.js"]