version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "80:80"
        restart: on-failure
        command: npm run start-dev